substitutions:
  _PUBLIC_MEDUSA_BACKEND_URL: "https://aynirape-backend-1093326509566.europe-west1.run.app"
  _PUBLIC_MEDUSA_PUBLISHABLE_KEY: "pk_c6b24335377cb6f54c7230d121c1a81e66adbecef50c59956c0bc72838367aae"
  _DEFAULT_REGION: "gb"
  _PUBLIC_SITE_URL: "https://aynirape.com"
  _PUBLIC_PAYPAL_CLIENT_ID: "ARspqmc1uS0d-DJ70ERG9FBN4-dfaKHjZaMvdoBdwRbTV8T8PeJTYEulFoVz2rHDFE26IQWmhZ4o327E"

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "apps/storefront/Dockerfile"
      - "-t"
      - "europe-west1-docker.pkg.dev/project-46ed8783-a1b4-42b9-9f5/aynirape/storefront:latest"
      - "--build-arg"
      - "PUBLIC_MEDUSA_BACKEND_URL=${_PUBLIC_MEDUSA_BACKEND_URL}"
      - "--build-arg"
      - "PUBLIC_MEDUSA_PUBLISHABLE_KEY=${_PUBLIC_MEDUSA_PUBLISHABLE_KEY}"
      - "--build-arg"
      - "DEFAULT_REGION=${_DEFAULT_REGION}"
      - "--build-arg"
      - "PUBLIC_SITE_URL=${_PUBLIC_SITE_URL}"
      - "--build-arg"
      - "PUBLIC_PAYPAL_CLIENT_ID=${_PUBLIC_PAYPAL_CLIENT_ID}"
      - "."
images:
  - "europe-west1-docker.pkg.dev/project-46ed8783-a1b4-42b9-9f5/aynirape/storefront:latest"

